title: "bind007, my personal journey."
email: "bind007@proton.me"
description: "Free space for engineering and tech."
baseurl: "" # no cambies esto
url: "https://bind007.github.io" # URL de tu blog

author:
  name: "bind007"
  email: "bind007@proton.me"

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
